### PR TITLE
add office equipment request workflow

### PR DESCRIPTION
**Pull request by ronlequoc**

### CODE REVIEW

**Comment by ronlequoc** [comment]
https://github.com/nccasia/workflow-w2/assets/133642247/461e0b13-9b5f-408f-a91c-0cb22a65d9d1

**Comment by ronlequoc** [comment]
Scenario: Request was rejected by Branch Manager.
https://github.com/nccasia/workflow-w2/assets/133642247/1ef26bc1-3e26-4e38-beb6-3df390f7ecfc

**Comment by ronlequoc** [comment]
Scenario: Request was rejected by IT.


https://github.com/nccasia/workflow-w2/assets/133642247/597dd7f1-e0a9-4492-a143-1022b0d7328e

**Comment by ronlequoc** [comment]
Scenario: Request was approved.

https://github.com/nccasia/workflow-w2/assets/133642247/f73da29a-ae94-4ca3-b990-70d7d5769832

**Comment by ronlequoc** [comment]
Testing enviroment (using fake email):
Staff email: ron.lequoc@ncc.asia
IT email: dekubaka2002@gmail.com
image
Head Office Email: 
image

**Comment by ronlequoc** [comment]
[UPDATED] Using textfield instead of richtext.
Define input for workflow as below
image

**Comment by ronlequoc** [comment]
[UPDATED] Scenario: Request was rejected by Branch Manager.


https://github.com/nccasia/workflow-w2/assets/133642247/e48fc2c5-1dc2-4d1b-bce6-15476c8f3e9c

**Comment by ronlequoc** [comment]
[UPDATED] Scenario: Request was rejected by IT.


https://github.com/nccasia/workflow-w2/assets/133642247/d57e53af-11ef-40cc-a3ad-073dcf5f8c41

**Comment by ronlequoc** [comment]
[UPDATED] Scenario: Request was approved.


https://github.com/nccasia/workflow-w2/assets/133642247/4ed615f9-7541-4c37-997f-1ef4b8f7b84f

**Comment by ronlequoc** [comment]
[UPDATED] Scenario: Send mail to selected branch manager.

[screen-capture.webm](https://github.com/nccasia/workflow-w2/assets/133642247/52ad5ade-f070-4a9e-9a10-3aca50f6422b)

**Review by thiendangncc — APPROVED** [review]

**Pull request merged**
